---
title: "Harry Potter Pedigree"
author: "Rachel Good"
date: "2023-10-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Create df

```{r create df}
hp_ped <- data.frame(fam = c("fam1","fam1","fam1","fam1","fam1","fam1","fam1","fam1","fam1","fam1","fam1","fam1","fam1","fam1","fam1","fam1","fam1","fam1","fam1","fam1","fam1","fam1","fam1","fam1","fam1","fam1","fam1", "fam1", "fam1", "fam1"), 
                      name = c("Vernon Dursley", "Marjorie Dursley", "Petunia Evans", "Lily Evans", "James Potter", "Dudley Dursley", "Harry Potter", "Ginny Weasley", "Arthur Weasley", "Molly Prewett", "Ron Weasley", "Fred Weasley", "George Weasley", "Percy Weasley", "Charlie Weasley", "Bill Weasley", "Hermione Granger", "Fleur Delacour", "Gabrielle Delacour", "Audrey Weasley", "James Potter II", "Albus Potter", "Lily Potter", "Rose Weasley", "Hugo Weasley", "Victoire Weasley", "Dominique Weasley", "Louis Weasley", "Molly Weasley", "Lucy Weasley" ), 
                      personID = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30"),
                      gen = c("1", "1", "1", "1", "1", "2", "2", "2", "1", "1", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3"),  
                      motherID = c("M1", "M1", "M2", "M2", "M3", "3", "4", "10", "M4", "M5", "10", "10", "10", "10", "10", "10", "M6", "M7", "M7", "M8", "8", "8", "8", "17", "17", "18", "18", "18", "20", "20"), 
                      fatherID = c("F1", "F1", "F2", "F2", "F3", "1", "5", "9", "F4", "F5", "9", "9", "9", "9", "9", "9", "F6", "F7", "F7", "F8", "7", "7", "7", "11", "11", "16", "16", "16", "14", "14"), 
                      spouseID = c("3", "NA", "1", "5", "4", "NA", "8", "7", "10", "9", "17", "NA", "NA", "20", "NA", "18", "11", "16", "NA", "14", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA"), 
                      sex = c("M", "F", "F", "F", "M", "M", "M", "F", "M", "F", "M", "M", "M", "M","M", "M", "F", "F", "F", "F", "M", "M", "F", "F", "M", "F", "F", "M", "F", "F") )


#audrey weasley - unknown maiden name
#James Potter II might not be correct, but I used it to differentiate grandson from grandfather

```

## Add additional people



```{r add row}
#hp_ped[nrow(hp_ped) + 1,] <- list(name, personID, gen, motherID, fatherID, spouseID, sex)
```


